[build]
  base = "Client/client"        # chemin du projet React depuis la racine du repo
  command = "npm run build"
  publish = "dist"              # Vite => "dist" ; CRA => "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
